eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7002/eureka/
server:
  port: 7008
spring:
  application:
    name: team-blog-article-service
  datasource:
    url: jdbc:mysql://localhost:3306/team_blog_article?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect:
        storage_engine: innodb